# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0c13b660ce66a74b087391df1ed64652b38a3da96a520d5cf05b49e1ef78863ad2a04ec162655ea44aef82d3de09e1ad72e54ac2234219e49b5b316ad5fdf72

test:
  secret_key_base: 9e56c2fe9a80110b5120f916e68ac00e6b7a70d6c50102f56c1ce141325982ca5173f1bf97de8a91826893a9945b4abbedbf5c53c8658ba69bc295aff652d7f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
